### ISSUE TITLE
Support signing with hardware security modules (HSMs)

### ISSUE THREAD

**Issue by charredlot** [russellhaering/goxmldsig#45]
We'd like to use HSMs with goxmldsig (and ultimately SAML) for signing, but right now the API requires an RSA private key. I'm not sure if there were any plans to add it, so I've made a pull request #44 that uses the golang `crypto.Signer` interface to accomplish this. There's also a few minor changes to enable ECDSA signing and verification. I've made the changes to preserve backwards compatibility so existing code won't break.

Please let me know if you have any questions about the use cases or would like a different approach.

**Comment by russellhaering** [comment]
Done in #89. Thanks for making it happen!
