### ISSUE TITLE
How to use for SOAP? (Could not sign: undeclared namespace prefix: 'SOAP-ENV')

### ISSUE THREAD

**Issue by gboor** [russellhaering/goxmldsig#66]
I sadly have to build a Soap client that also supports WSSE signing for messages for interaction with some legacy system. I'm looking into this library to see if I can use it to generate the required signature before sending the message off.

The first problem I ran into is that, for signing SOAP messages, only the body element should be signed. But if I try to do that, the signature generator complains that the namespace is not defined. Which is true; the namespace is defined on the envelope, not deeper down.

Test code;

```
package main

import (
	"crypto/tls"
	"fmt"
	"log"

	"github.com/beevik/etree"
	"github.com/russellhaering/goxmldsig"
)

func failOnError(err error, msg string) {
	if err != nil {
		log.Fatalf("%s: %s", msg, err)
	}
}

func main() {
	certBytes := []byte(`-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
`)

	keyBytes := []byte(`-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
`)

	xmlBytes := []byte(`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://sys.svc.tennet.nl/MMCHub/v1" xmlns:ns2="http://sys.svc.tennet.nl/MMCHub/Header/v1">
   <SOAP-ENV:Header>
      <ns2:MessageAddressing>
         <ns2:technicalMessageId>0849df0a-1912-11eb-8b2d-6c5d3a074dc2</ns2:technicalMessageId>
         <ns2:senderId>8720299053908</ns2:senderId>
         <ns2:receiverId>8716867999983</ns2:receiverId>
         <ns2:carrierId>8719333014463</ns2:carrierId>
         <ns2:contentType>ACK_ACTIVATED_FCR</ns2:contentType>
      </ns2:MessageAddressing>
   </SOAP-ENV:Header>
   <SOAP-ENV:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
      <ns1:getMessageRequest>
         <ns1:technicalMessageId>3c72e741-190e-11eb-86d0-c0b6f97cb937</ns1:technicalMessageId>
      </ns1:getMessageRequest>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`)

	keyPair, err := tls.X509KeyPair(certBytes, keyBytes)
	failOnError(err, "Invalid keypair")

	keyStore := dsig.TLSCertKeyStore(keyPair)
	ctx := dsig.NewDefaultSigningContext(keyStore)
	ctx.Canonicalizer = dsig.MakeC14N10ExclusiveCanonicalizerWithPrefixList("")
	err = ctx.SetSignatureMethod(dsig.RSASHA256SignatureMethod)
	failOnError(err, "Failed to set signature mode")

	readXMLDoc := etree.NewDocument()
	err = readXMLDoc.ReadFromBytes(xmlBytes)
	failOnError(err, "Cannot parse XML doc")

	elementToSign := readXMLDoc.Root().FindElement("Body")
	elementToSign.CreateAttr("ID", "id1234")

	signedElement, err := ctx.SignEnveloped(elementToSign)
	failOnError(err, "Could not sign")

	var signedBuf []byte
	readXMLDoc.SetRoot(signedElement)
	signedBuf, err = readXMLDoc.WriteToBytes()
	failOnError(err, "Failed to write to bytes")

	fmt.Println(string(signedBuf))
}
```

Errors out with; Could not sign: undeclared namespace prefix: 'SOAP-ENV'

Is there any way to get this to work, or am I trying to do something incredibly unholy here?

Full disclaimer; I know very little about SOAP and only a moderate amount about xml signatures, so perhaps this is a really obvious question. I previously tried to write this client in Python, but an issue in the way it handles signatures makes it not viable. I also built a test implementation in PHP, which works, but I'm extremely reluctant to use that for a production deployment.

Hope someone can help me out a bit here :)

**Comment by muhRobai** [comment]
i think you can using struct tag like this, for set prefix SOAP-ENV
```
//swagger:model Envelop
type Envelope struct {
	XMLName      xml.Name   `xml:"SOAP-ENV:Envelope"`
	XSDAttr      string     `xml:"xmlns:xsd,attr"`
	XSIAttr      string     `xml:"xmlns:xsi,attr"`
	EnvelopeAttr string     `xml:"xmlns:SOAP-ENV,attr"`
	SoapEncAttr  string     `xml:"xmlns:SOAP-ENC,attr"`
	Body         ThreeParty `xml:"SOAP-ENV:Body"`
}
```

**Comment by gboor** [comment]
Thanks for the idea, but that sadly does not work, since the whole document already exists before I sign it and the namespace is not on the <Body> node.

I noticed that implementations of C14N in other languages actually copies the namespace from parent nodes when you try to canonicalize a single node, but this library does not...

Is there some way to fix that?

**Comment by creativesuraj** [comment]
@gboor Are you able to sign the SOAP xml?
I'm stuck with signing SOAP xml payload in Go. Didn't find a working library yet.

Thanks

**Comment by gboor** [comment]
@creativesuraj I was never able to make it work with SOAP. I switched the whole code base to Python eventually. Sorry I can't be more helpful.

**Comment by creativesuraj** [comment]
@gboor which python library are you using?

**Comment by gboor** [comment]
@creativesuraj https://docs.python-zeep.org/en/master/

**Comment by creativesuraj** [comment]
Thanks
